from ..ResumeAI.prompts import (
    EXTRACTION_SYSTEM_INSTRUCTION,
    EXTRACTION_PROMPT_TEMPLATE,
    CRITIQUE_PROMPT_TEMPLATE,
    REFINEMENT_PROMPT_TEMPLATE,
    BULLET_GENERATION_PROMPT_TEMPLATE,
)

__all__ = [
    "EXTRACTION_SYSTEM_INSTRUCTION",
    "EXTRACTION_PROMPT_TEMPLATE",
    "CRITIQUE_PROMPT_TEMPLATE",
    "REFINEMENT_PROMPT_TEMPLATE",
    "BULLET_GENERATION_PROMPT_TEMPLATE",
]
