/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedInterviewIndexRouteImport } from './routes/_authenticated.interview.index'
import { Route as AuthenticatedInterviewCodingRouteImport } from './routes/_authenticated.interview.coding'
import { Route as AuthenticatedInterviewDsaRouteImport } from './routes/_authenticated.interview.dsa'
import { Route as AuthenticatedInterviewHrRouteImport } from './routes/_authenticated.interview.hr'
import { Route as AuthenticatedInterviewProjectRouteImport } from './routes/_authenticated.interview.project'
import { Route as AuthenticatedInterviewSetupRouteImport } from './routes/_authenticated.interview.setup'
import { Route as AuthenticatedInterviewTechnicalRouteImport } from './routes/_authenticated.interview.technical'
import { Route as AuthenticatedResumeIndexRouteImport } from './routes/_authenticated.resume.index'
import { Route as AuthenticatedResumeAnalyzeRouteImport } from './routes/_authenticated.resume.analyze'
import { Route as AuthenticatedResumeCreateRouteImport } from './routes/_authenticated.resume.create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInterviewIndexRoute =
  AuthenticatedInterviewIndexRouteImport.update({
    id: '/interview/',
    path: '/interview/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewCodingRoute =
  AuthenticatedInterviewCodingRouteImport.update({
    id: '/interview/coding',
    path: '/interview/coding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewDsaRoute =
  AuthenticatedInterviewDsaRouteImport.update({
    id: '/interview/dsa',
    path: '/interview/dsa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewHrRoute =
  AuthenticatedInterviewHrRouteImport.update({
    id: '/interview/hr',
    path: '/interview/hr',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewProjectRoute =
  AuthenticatedInterviewProjectRouteImport.update({
    id: '/interview/project',
    path: '/interview/project',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewSetupRoute =
  AuthenticatedInterviewSetupRouteImport.update({
    id: '/interview/setup',
    path: '/interview/setup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewTechnicalRoute =
  AuthenticatedInterviewTechnicalRouteImport.update({
    id: '/interview/technical',
    path: '/interview/technical',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResumeIndexRoute =
  AuthenticatedResumeIndexRouteImport.update({
    id: '/resume/',
    path: '/resume/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResumeAnalyzeRoute =
  AuthenticatedResumeAnalyzeRouteImport.update({
    id: '/resume/analyze',
    path: '/resume/analyze',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResumeCreateRoute =
  AuthenticatedResumeCreateRouteImport.update({
    id: '/resume/create',
    path: '/resume/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/interview/coding': typeof AuthenticatedInterviewCodingRoute
  '/interview/dsa': typeof AuthenticatedInterviewDsaRoute
  '/interview/hr': typeof AuthenticatedInterviewHrRoute
  '/interview/project': typeof AuthenticatedInterviewProjectRoute
  '/interview/setup': typeof AuthenticatedInterviewSetupRoute
  '/interview/technical': typeof AuthenticatedInterviewTechnicalRoute
  '/resume/analyze': typeof AuthenticatedResumeAnalyzeRoute
  '/resume/create': typeof AuthenticatedResumeCreateRoute
  '/interview/': typeof AuthenticatedInterviewIndexRoute
  '/resume/': typeof AuthenticatedResumeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/interview/coding': typeof AuthenticatedInterviewCodingRoute
  '/interview/dsa': typeof AuthenticatedInterviewDsaRoute
  '/interview/hr': typeof AuthenticatedInterviewHrRoute
  '/interview/project': typeof AuthenticatedInterviewProjectRoute
  '/interview/setup': typeof AuthenticatedInterviewSetupRoute
  '/interview/technical': typeof AuthenticatedInterviewTechnicalRoute
  '/resume/analyze': typeof AuthenticatedResumeAnalyzeRoute
  '/resume/create': typeof AuthenticatedResumeCreateRoute
  '/interview': typeof AuthenticatedInterviewIndexRoute
  '/resume': typeof AuthenticatedResumeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/interview/coding': typeof AuthenticatedInterviewCodingRoute
  '/_authenticated/interview/dsa': typeof AuthenticatedInterviewDsaRoute
  '/_authenticated/interview/hr': typeof AuthenticatedInterviewHrRoute
  '/_authenticated/interview/project': typeof AuthenticatedInterviewProjectRoute
  '/_authenticated/interview/setup': typeof AuthenticatedInterviewSetupRoute
  '/_authenticated/interview/technical': typeof AuthenticatedInterviewTechnicalRoute
  '/_authenticated/resume/analyze': typeof AuthenticatedResumeAnalyzeRoute
  '/_authenticated/resume/create': typeof AuthenticatedResumeCreateRoute
  '/_authenticated/interview/': typeof AuthenticatedInterviewIndexRoute
  '/_authenticated/resume/': typeof AuthenticatedResumeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/interview/coding'
    | '/interview/dsa'
    | '/interview/hr'
    | '/interview/project'
    | '/interview/setup'
    | '/interview/technical'
    | '/resume/analyze'
    | '/resume/create'
    | '/interview/'
    | '/resume/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/interview/coding'
    | '/interview/dsa'
    | '/interview/hr'
    | '/interview/project'
    | '/interview/setup'
    | '/interview/technical'
    | '/resume/analyze'
    | '/resume/create'
    | '/interview'
    | '/resume'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/interview/coding'
    | '/_authenticated/interview/dsa'
    | '/_authenticated/interview/hr'
    | '/_authenticated/interview/project'
    | '/_authenticated/interview/setup'
    | '/_authenticated/interview/technical'
    | '/_authenticated/resume/analyze'
    | '/_authenticated/resume/create'
    | '/_authenticated/interview/'
    | '/_authenticated/resume/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interview/': {
      id: '/_authenticated/interview/'
      path: '/interview'
      fullPath: '/interview/'
      preLoaderRoute: typeof AuthenticatedInterviewIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interview/coding': {
      id: '/_authenticated/interview/coding'
      path: '/interview/coding'
      fullPath: '/interview/coding'
      preLoaderRoute: typeof AuthenticatedInterviewCodingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interview/dsa': {
      id: '/_authenticated/interview/dsa'
      path: '/interview/dsa'
      fullPath: '/interview/dsa'
      preLoaderRoute: typeof AuthenticatedInterviewDsaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interview/hr': {
      id: '/_authenticated/interview/hr'
      path: '/interview/hr'
      fullPath: '/interview/hr'
      preLoaderRoute: typeof AuthenticatedInterviewHrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interview/project': {
      id: '/_authenticated/interview/project'
      path: '/interview/project'
      fullPath: '/interview/project'
      preLoaderRoute: typeof AuthenticatedInterviewProjectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interview/setup': {
      id: '/_authenticated/interview/setup'
      path: '/interview/setup'
      fullPath: '/interview/setup'
      preLoaderRoute: typeof AuthenticatedInterviewSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interview/technical': {
      id: '/_authenticated/interview/technical'
      path: '/interview/technical'
      fullPath: '/interview/technical'
      preLoaderRoute: typeof AuthenticatedInterviewTechnicalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resume/': {
      id: '/_authenticated/resume/'
      path: '/resume'
      fullPath: '/resume/'
      preLoaderRoute: typeof AuthenticatedResumeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resume/analyze': {
      id: '/_authenticated/resume/analyze'
      path: '/resume/analyze'
      fullPath: '/resume/analyze'
      preLoaderRoute: typeof AuthenticatedResumeAnalyzeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resume/create': {
      id: '/_authenticated/resume/create'
      path: '/resume/create'
      fullPath: '/resume/create'
      preLoaderRoute: typeof AuthenticatedResumeCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedInterviewCodingRoute: typeof AuthenticatedInterviewCodingRoute
  AuthenticatedInterviewDsaRoute: typeof AuthenticatedInterviewDsaRoute
  AuthenticatedInterviewHrRoute: typeof AuthenticatedInterviewHrRoute
  AuthenticatedInterviewProjectRoute: typeof AuthenticatedInterviewProjectRoute
  AuthenticatedInterviewSetupRoute: typeof AuthenticatedInterviewSetupRoute
  AuthenticatedInterviewTechnicalRoute: typeof AuthenticatedInterviewTechnicalRoute
  AuthenticatedResumeAnalyzeRoute: typeof AuthenticatedResumeAnalyzeRoute
  AuthenticatedResumeCreateRoute: typeof AuthenticatedResumeCreateRoute
  AuthenticatedInterviewIndexRoute: typeof AuthenticatedInterviewIndexRoute
  AuthenticatedResumeIndexRoute: typeof AuthenticatedResumeIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedInterviewCodingRoute: AuthenticatedInterviewCodingRoute,
  AuthenticatedInterviewDsaRoute: AuthenticatedInterviewDsaRoute,
  AuthenticatedInterviewHrRoute: AuthenticatedInterviewHrRoute,
  AuthenticatedInterviewProjectRoute: AuthenticatedInterviewProjectRoute,
  AuthenticatedInterviewSetupRoute: AuthenticatedInterviewSetupRoute,
  AuthenticatedInterviewTechnicalRoute: AuthenticatedInterviewTechnicalRoute,
  AuthenticatedResumeAnalyzeRoute: AuthenticatedResumeAnalyzeRoute,
  AuthenticatedResumeCreateRoute: AuthenticatedResumeCreateRoute,
  AuthenticatedInterviewIndexRoute: AuthenticatedInterviewIndexRoute,
  AuthenticatedResumeIndexRoute: AuthenticatedResumeIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
